# Chapter 2 - Tensors

## Simple CPU Example

In [16]:
import torch

x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
z = x + y
print(z)
# out:
#  tensor([[ 8, 10, 12], [14, 16, 18]])
print(torch.cuda.is_available())
print(z.size())
# out: torch.Size([2, 3])

tensor([[ 8, 10, 12],
        [14, 16, 18]])
True
torch.Size([2, 3])


## Simple GPU Example

In [3]:
device = "cuda" if torch.cuda.is_available() \
  else "cpu"
x = torch.tensor([[1,2,3],[4,5,6]], device=device)
y = torch.tensor([[7,8,9],[10,11,12]],
device=device)
z = x + y
print(z)
# out:
#   tensor([[ 8, 10, 12],
#          [14, 16, 18]], device='cuda:0')

print(z.size())
# out: torch.Size([2, 3])

print(z.device)
# out: cuda:0

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
torch.Size([2, 3])
cuda:0


## Moving Tensors between CPU & GPU

In [4]:
device = "cuda" if torch.cuda.is_available() \
  else "cpu"
x.to(device)
y.to(device)
z = x + y
z.to("cpu")
# out:
# tensor([[ 8, 10, 12],
#         [14, 16, 18]])

tensor([[ 8, 10, 12],
        [14, 16, 18]])

# Creating Tensors

In [8]:
import numpy

# Created from pre-existing arrays
w = torch.tensor([1,2,3]) # <1>
w = torch.tensor((1,2,3)) # <2>
w = torch.tensor(numpy.array([1,2,3])) # <3>

# Initialized by size
w = torch.empty(100,200) # <4>


w = torch.zeros(100,200) # <5>

w = torch.ones(100,200)  # <6>


tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])


1. from a list
2. from a tuple
3. from a numpy array
4. uninitialized, elements values are not predictable
5. all elements initialized with 0.0
6. all elements initialized with 1.0

In [13]:
# Initialized by size with random values
w = torch.rand(100,200)     # <1>
w = torch.randn(100,200)    # <2>
w = torch.randint(5,10,(100,200))  # <3>

# Initialized with specified data type or device
w = torch.empty((100,200), dtype=torch.float64,
                device="cuda")

# Initialized to have same size, data type,
#   and device as another tensor
x = torch.empty_like(w)
print(x)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)


1. Creates a 100 x 200 tensor with elements from a uniform distribution on the interval [0, 1)
2. elements are random numbers from a normal distribution with mean 0 and variance 1
3. elements are random integers between 5 and 10

## Data Types

In [ ]:
# Specify data type at creation using dtype
w = torch.tensor([1,2,3], dtype=torch.float32)

# Use casting method to cast to a new data type
w.int()       # w remains a float32 after cast
w = w.int()   # w changes to int32 after cast

# Use to() method to cast to a new type
w = w.to(torch.float64) # <1>
w = w.to(dtype=torch.float64) # <2>

# Python automatically converts data types during operations
x = torch.tensor([1,2,3], dtype=torch.int32)
y = torch.tensor([1,2,3], dtype=torch.float32)
z = x + y # <3>
print(z.dtype)

torch.float32


## Tensor Operations

In [ ]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)
# out:
# tensor([[1, 2],
#         [3, 4],
#         [5, 6],
#         [7, 8]])

# Indexing, returns a tensor
print(x[1,1])
# out: tensor(4)

# Indexing, returns value as Python number
print(x[1,1].item())
# out: 4

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor(4)
4


In [ ]:
# Slicing
print(x[:2,1])
# out: tensor([2, 4])

# Boolean indexing
# Only keep elements less than 5
print(x[x<5])
# out: tensor([1, 2, 3, 4])

tensor([2, 4])
tensor([1, 2, 3, 4])


In [ ]:
# Transpose array, x.t() or x.T can be used
print(x.t())
# tensor([[1, 3, 5, 7],
#         [2, 4, 6, 8]])

# Changing shape, Usually view() is preferred over reshape()
print(x.view((2,4)))
# tensor([[1, 3, 5, 7],
#         [2, 4, 6, 8]])

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
# Combining tensors
y = torch.stack((x, x))
print(y)
# out:
# tensor([[[1, 2],
#          [3, 4],
#          [5, 6],
#          [7, 8]],

#         [[1, 2],
#          [3, 4],
#          [5, 6],
#          [7, 8]]])

# Splitting tensors
a,b = x.unbind(dim=1)
print(a,b)
# out:
#  tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])


## Automatic Differentiation (Autograd)

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]],
         dtype=torch.float, requires_grad=True)
print(x)
# out:
# tensor([[1., 2., 3.],
#         [4., 5., 6.]], requires_grad=True)

f = x.pow(2).sum()
print(f)
# tensor(91., grad_fn=<SumBackward0>)

f.backward()
print(x.grad) # df/dx = 2x
# tensor([[ 2.,  4.,  6.],
#         [ 8., 10., 12.]])

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
tensor(91., grad_fn=<SumBackward0>)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
